[deps]
ClimaCore = "d414da3d-4745-48bb-8d80-42e94e092884"
ClimaDiagnostics = "1ecacbb8-0713-4841-9a07-eb5aa8a2d53f"
ClimaUtilities = "b3f4f4ca-9299-4f7f-bd9b-81e1242a7513"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
ClimaCore = "0.14.41"
ClimaUtilities = "0.1.22"
Documenter = "1"
